'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ar' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.business': 'For Schools',
    'nav.blog': 'Blog',
    'nav.get-started': 'Get Started',

    // Home Page
    'home.hero.title': 'Your AI Coach for Mind, Sleep, and Well-Being',
    'home.hero.subtitle': 'Empower your mental health journey with personalized voice coaching, self‑discovery, daily support, mood awareness, better sleep & mindfulness.',
    'home.hero.download': 'Download App',
    'home.hero.learn-more': 'Learn More',

    // Features
    'features.title': 'Everything You Need for Mental Wellness',
    'features.ai-coach': 'AI Voice Coach',
    'features.ai-coach-desc': 'Get personalized guidance and support from your AI wellness coach, available 24/7.',
    'features.journaling': 'Smart Journaling',
    'features.journaling-desc': 'Express your thoughts with AI-powered prompts and insights to enhance self-reflection.',
    'features.mood-tracker': 'Mood Tracking',
    'features.mood-tracker-desc': 'Monitor your emotional patterns and discover what influences your well-being.',
    'features.sleep-insights': 'Sleep Insights',
    'features.sleep-insights-desc': 'Understand your sleep patterns and get personalized recommendations for better rest.',
    'features.meditation': 'Guided Meditation',
    'features.meditation-desc': 'Access a library of meditation sessions tailored to your needs and preferences.',
    'features.tracking': 'Progress Tracking',
    'features.tracking-desc': 'Visualize your wellness journey with detailed analytics and progress reports.',
    'features.affirmations': 'Daily Affirmations',
    'features.affirmations-desc': 'Start each day with personalized affirmations to boost confidence and positivity.',
    'features.challenges': 'Wellness Challenges',
    'features.challenges-desc': 'Participate in guided challenges to build healthy habits and achieve your goals.',

    // How It Works
    'how-it-works.title': 'How NuviaMind Works',
    'how-it-works.step1': 'Download & Setup',
    'how-it-works.step1-desc': 'Download the app and complete your personalized wellness assessment.',
    'how-it-works.step2': 'Get Personalized Coaching',
    'how-it-works.step2-desc': 'Receive AI-powered insights and coaching tailored to your unique needs.',
    'how-it-works.step3': 'Track Your Progress',
    'how-it-works.step3-desc': 'Monitor your wellness journey and celebrate your achievements.',

    // Testimonials
    'testimonials.title': 'What Our Users Say',
    'testimonials.1': 'NuviaMind has completely transformed my approach to mental wellness. The AI coach feels like having a personal therapist available anytime.',
    'testimonials.1-author': 'Sarah M.',
    'testimonials.2': 'The sleep insights have helped me understand my patterns and improve my rest quality significantly.',
    'testimonials.2-author': 'Michael R.',
    'testimonials.3': 'I love the journaling feature with AI prompts. It helps me reflect deeper on my thoughts and emotions.',
    'testimonials.3-author': 'Emma L.',

    // Pricing Preview
    'pricing-preview.title': 'Choose Your Wellness Plan',
    'pricing-preview.free': 'Free',
    'pricing-preview.plus': 'Plus',
    'pricing-preview.premium': 'Premium',
    'pricing-preview.free-desc': 'Basic wellness tracking',
    'pricing-preview.plus-desc': 'AI coaching & insights',
    'pricing-preview.premium-desc': 'Complete wellness suite',
    'pricing-preview.cta': 'View All Plans',

    // Pricing Page
    'pricing.title': 'Choose Your Plan',
    'pricing.subtitle': 'Start your wellness journey with the plan that fits your needs.',
    'pricing.monthly': 'Monthly',
    'pricing.annual': 'Annual',
    'pricing.save': 'Save 50%',

    // Free Plan
    'pricing.free.name': 'Free',
    'pricing.free.price': '$0',
    'pricing.free.period': '/month',
    'pricing.free.annual-price': '$0',
    'pricing.free.annual-period': '/year',
    'pricing.free.description': 'Perfect for getting started with basic wellness tracking.',
    'pricing.free.feature1': 'Basic mood tracking',
    'pricing.free.feature2': '5 journal entries per month',
    'pricing.free.feature3': 'Basic sleep insights',
    'pricing.free.feature4': 'Limited meditation library',
    'pricing.free.not-included1': 'AI voice coaching',
    'pricing.free.not-included2': 'Advanced analytics',
    'pricing.free.not-included3': 'Unlimited journaling',
    'pricing.free.not-included4': 'Premium meditation content',
    'pricing.free.button': 'Get Started Free',

    // Plus Plan
    'pricing.plus.name': 'Plus',
    'pricing.plus.price': '$4.99',
    'pricing.plus.period': '/month',
    'pricing.plus.annual-price': '$29.94',
    'pricing.plus.annual-period': '/year',
    'pricing.plus.description': 'Enhanced features with AI coaching for deeper insights.',
    'pricing.plus.feature1': 'Everything in Free',
    'pricing.plus.feature2': 'AI voice coaching sessions',
    'pricing.plus.feature3': 'Unlimited journaling',
    'pricing.plus.feature4': 'Advanced mood analytics',
    'pricing.plus.feature5': 'Personalized insights',
    'pricing.plus.feature6': 'Extended meditation library',
    'pricing.plus.not-included1': 'Priority support',
    'pricing.plus.not-included2': 'Advanced sleep analysis',
    'pricing.plus.button': 'Start Plus Plan',

    // Premium Plan
    'pricing.premium.name': 'Premium',
    'pricing.premium.price': '$9.99',
    'pricing.premium.period': '/month',
    'pricing.premium.annual-price': '$59.94',
    'pricing.premium.annual-period': '/year',
    'pricing.premium.description': 'Complete wellness suite with all features and priority support.',
    'pricing.premium.feature1': 'Everything in Plus',
    'pricing.premium.feature2': 'Advanced sleep analysis',
    'pricing.premium.feature3': 'Priority customer support',
    'pricing.premium.feature4': 'Advance Wellness challenges',
    'pricing.premium.feature5': 'Export data & reports',
    'pricing.premium.feature6': 'Certifications',
    'pricing.premium.feature7': 'Advance Daily Affirmations',
    'pricing.premium.feature8': 'Early access to new features',
    'pricing.premium.feature9': 'Personalized wellness plans',
    'pricing.premium.button': 'Start Premium Plan',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about NuviaMind.',
    'faq.question1': 'Can I change my plan anytime?',
    'faq.answer1': 'Yes, you can upgrade or downgrade your plan at any time. Changes will be reflected in your next billing cycle.',
    'faq.question2': 'Is there a free trial?',
    'faq.answer2': 'We offer a free plan with basic features. You can upgrade to Plus or Premium anytime to access advanced features.',
    'faq.question3': 'How does the AI coaching work?',
    'faq.answer3': 'Our AI coach provides personalized guidance based on your mood patterns, journal entries, and wellness goals using advanced machine learning.',

    // About Page
    'about.title': 'About NuviaMind',
    'about.subtitle': 'We\'re on a mission to make mental wellness accessible to everyone through innovative AI technology.',
    'about.mission.title': 'Our Mission',
    'about.mission.content': 'To democratize mental wellness by providing personalized, AI-powered coaching that adapts to each individual\'s unique needs and circumstances.',
    'about.story.title': 'Our Story',
    'about.story.content': 'Founded by mental health professionals and AI experts, NuviaMind was born from the recognition that traditional mental health resources aren\'t accessible to everyone.',
    'about.values.title': 'Our Values',
    'about.values.privacy.title': 'Privacy First',
    'about.values.privacy.desc': 'Your mental health data is sacred. We use end-to-end encryption and never share your personal information.',
    'about.values.accessibility.title': 'Accessible to All',
    'about.values.accessibility.desc': 'Mental wellness shouldn\'t be a luxury. We\'re committed to making our tools affordable and inclusive.',
    'about.values.evidence.title': 'Evidence-Based',
    'about.values.evidence.desc': 'Our approaches are grounded in scientific research and validated therapeutic techniques.',
    'about.impact.title': 'Our Impact',
    'about.impact.users': 'Active Users',
    'about.impact.sessions': 'Coaching Sessions',
    'about.impact.satisfaction': 'User Satisfaction',

    // Contact Page
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions or need support? We\'re here to help you on your wellness journey.',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email Address',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.email-support': 'Email Support',
    'contact.response-time': 'We typically respond within 24 hours',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.1.q': 'How do I reset my password?',
    'contact.faq.1.a': 'You can reset your password by clicking "Forgot Password" on the login screen and following the instructions sent to your email.',
    'contact.faq.2.q': 'Is my data secure?',
    'contact.faq.2.a': 'Yes, we use end-to-end encryption and follow industry best practices to protect your personal information.',
    'contact.faq.3.q': 'Can I cancel my subscription anytime?',
    'contact.faq.3.a': 'Absolutely. You can cancel your subscription at any time through your account settings or app store.',

    // Business Page
    'business.title': 'NuviaMind for Schools',
    'business.subtitle': 'Support student mental health and well-being with our comprehensive wellness platform designed for educational institutions.',
    'business.benefits.student-wellbeing.title': 'Student Well-being',
    'business.benefits.student-wellbeing.desc': 'Provide students with 24/7 access to mental health support and wellness resources.',
    'business.benefits.analytics.title': 'Analytics & Insights',
    'business.benefits.analytics.desc': 'Get anonymized insights into student wellness trends to inform support programs.',
    'business.benefits.privacy.title': 'Privacy & Security',
    'business.benefits.privacy.desc': 'FERPA-compliant platform with robust privacy protections for student data.',
    'business.benefits.management.title': 'Easy Management',
    'business.benefits.management.desc': 'Simple admin dashboard to manage student accounts and monitor engagement.',
    'business.packages.title': 'Choose Your Package',
    'business.packages.small.title': 'Small School',
    'business.packages.small.students': 'Up to 1,000 students',
    'business.packages.small.price': '$2.99/student/month',
    'business.packages.small.features.1': 'Basic wellness tracking',
    'business.packages.small.features.2': 'AI coaching sessions',
    'business.packages.small.features.3': 'Admin dashboard',
    'business.packages.small.features.4': 'Email support',
    'business.packages.medium.title': 'Medium School',
    'business.packages.medium.students': '1,000 - 5,000 students',
    'business.packages.medium.price': '$2.49/student/month',
    'business.packages.medium.features.1': 'Everything in Small',
    'business.packages.medium.features.2': 'Advanced analytics',
    'business.packages.medium.features.3': 'Custom branding',
    'business.packages.medium.features.4': 'Priority support',
    'business.packages.large.title': 'Large School',
    'business.packages.large.students': '5,000+ students',
    'business.packages.large.price': 'Custom pricing',
    'business.packages.large.features.1': 'Everything in Medium',
    'business.packages.large.features.2': 'Dedicated account manager',
    'business.packages.large.features.3': 'Custom integrations',
    'business.packages.large.features.4': '24/7 phone support',
    'business.form.title': 'Get Started Today',
    'business.form.subtitle': 'Contact us to learn more about bringing NuviaMind to your school.',
    'business.form.school-name': 'School Name',
    'business.form.student-count': 'Number of Students',
    'business.form.student-count.placeholder': 'Select student count',
    'business.form.student-count.less-1000': 'Less than 1,000',
    'business.form.student-count.1000-5000': '1,000 - 5,000',
    'business.form.student-count.5000-10000': '5,000 - 10,000',
    'business.form.student-count.10000-plus': '10,000+',
    'business.form.contact-person': 'Contact Person',
    'business.form.email': 'Email Address',
    'business.form.notes': 'Additional Notes',
    'business.form.notes.placeholder': 'Tell us about your specific needs or questions...',
    'business.form.submit': 'Request Information',

    // Footer
    'footer.company': 'Empowering mental wellness through AI-powered coaching and personalized insights.',
    'footer.quick-links': 'Quick Links',
    'footer.resources': 'Resources',
    'footer.legal': 'Legal',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms & Conditions',
    'footer.legal.medical': 'Medical Disclaimer',
    'footer.legal.cookies': 'Cookie Policy',
    'footer.legal.refund': 'Refund Policy',
    'footer.legal.data-deletion': 'Data Deletion',
    'footer.legal.eula': 'EULA',
    'footer.legal.accessibility': 'Accessibility',
    'footer.legal.security-practices': 'Security Practices',
    'footer.copyright': '© 2025 NuviaMind. All rights reserved.',

    // Live Chat
    'chat.welcome': "Hi! I'm here to help you with any questions about NuviaMind. How can I assist you today?",
    'chat.response': "Thanks for your message! A support agent will respond shortly. In the meantime, you can check our FAQ or contact us at support@nuviamind.com",
    'chat.tooltip': 'Chat with us!',
    'chat.title': 'Live Support',
    'chat.subtitle': "We're here to help!",
    'chat.placeholder': 'Type your message...',

    // Cookie Consent
    'cookie-consent.title': 'Privacy-Friendly Analytics',
    'cookie-consent.subtitle': 'Help us improve your experience',
    'cookie-consent.description': 'We use privacy-friendly analytics to understand how visitors use our website. No personal data, cookies, or tracking across other sites.',
    'cookie-consent.what-we-track': 'What we track:',
    'cookie-consent.track.page-views': 'Anonymous page views',
    'cookie-consent.track.button-clicks': 'Button clicks and interactions',
    'cookie-consent.track.navigation': 'Navigation patterns',
    'cookie-consent.track.referrers': 'Traffic sources',
    'cookie-consent.what-we-dont-track': 'What we DON\'T track:',
    'cookie-consent.no-track.personal-info': 'Personal information or IP addresses',
    'cookie-consent.no-track.cross-site': 'Cross-site tracking',
    'cookie-consent.no-track.cookies': 'Tracking cookies',
    'cookie-consent.no-track.health-data': 'Health or sensitive data',
    'cookie-consent.learn-more': 'Learn more about our tracking',
    'cookie-consent.show-less': 'Show less',
    'cookie-consent.accept': 'Accept Analytics',
    'cookie-consent.decline': 'Decline',
    'cookie-consent.policy-link-text': 'Read our',
    'cookie-consent.privacy-policy': 'Privacy Policy',
    'cookie-consent.and': 'and',
    'cookie-consent.cookie-policy': 'Cookie Policy',

    // Security Form
    'security-form.notice': 'This form is secured with encryption and privacy protection',
    'security-form.data-notice': 'Your data is encrypted and protected. We never store personal information unnecessarily.',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'حولنا',
    'nav.pricing': 'الأسعار',
    'nav.contact': 'اتصل بنا',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.business': 'للمدارس',
    'nav.blog': 'المدونة',
    'nav.get-started': 'ابدأ الآن',

    // Home Page
    'home.hero.title': 'مدربك الذكي للعقل والنوم والرفاهية',
    'home.hero.subtitle': 'قوّي رحلة صحتك النفسية بالتدريب الصوتي المخصص واكتشاف الذات والدعم اليومي ووعي المزاج والنوم الأفضل واليقظة الذهنية.',
    'home.hero.download': 'تحميل التطبيق',
    'home.hero.learn-more': 'اعرف المزيد',

    // Features
    'features.title': 'كل ما تحتاجه للعافية النفسية',
    'features.ai-coach': 'مدرب صوتي ذكي',
    'features.ai-coach-desc': 'احصل على إرشاد ودعم مخصص من مدرب العافية الذكي، متاح على مدار الساعة.',
    'features.journaling': 'كتابة يوميات ذكية',
    'features.journaling-desc': 'عبّر عن أفكارك بمطالبات ورؤى مدعومة بالذكاء الاصطناعي لتعزيز التأمل الذاتي.',
    'features.mood-tracker': 'تتبع المزاج',
    'features.mood-tracker-desc': 'راقب أنماطك العاطفية واكتشف ما يؤثر على رفاهيتك.',
    'features.sleep-insights': 'تحليلات النوم',
    'features.sleep-insights-desc': 'افهم أنماط نومك واحصل على توصيات مخصصة لراحة أفضل.',
    'features.meditation': 'تأمل موجه',
    'features.meditation-desc': 'اوصل إلى مكتبة من جلسات التأمل المصممة حسب احتياجاتك وتفضيلاتك.',
    'features.tracking': 'تتبع التقدم',
    'features.tracking-desc': 'تصور رحلة عافيتك بتحليلات مفصلة وتقارير تقدم.',
    'features.affirmations': 'تأكيدات يومية',
    'features.affirmations-desc': 'ابدأ كل يوم بتأكيدات مخصصة لتعزيز الثقة والإيجابية.',
    'features.challenges': 'تحديات العافية',
    'features.challenges-desc': 'شارك في تحديات موجهة لبناء عادات صحية وتحقيق أهدافك.',

    // How It Works
    'how-it-works.title': 'كيف يعمل نوفيا مايند',
    'how-it-works.step1': 'التحميل والإعداد',
    'how-it-works.step1-desc': 'حمّل التطبيق وأكمل تقييم العافية المخصص لك.',
    'how-it-works.step2': 'احصل على تدريب مخصص',
    'how-it-works.step2-desc': 'تلقّ رؤى وتدريب مدعوم بالذكاء الاصطناعي مصمم حسب احتياجاتك الفريدة.',
    'how-it-works.step3': 'تتبع تقدمك',
    'how-it-works.step3-desc': 'راقب رحلة عافيتك واحتفل بإنجازاتك.',

    // Testimonials
    'testimonials.title': 'ما يقوله مستخدمونا',
    'testimonials.1': 'نوفيا مايند غيّر تماماً نهجي في العافية النفسية. المدرب الذكي يشعر وكأن لديك معالج شخصي متاح في أي وقت.',
    'testimonials.1-author': 'سارة م',
    'testimonials.2': 'تحليلات النوم ساعدتني في فهم أنماطي وتحسين جودة راحتي بشكل كبير.',
    'testimonials.2-author': 'أحمد ر',
    'testimonials.3': 'أحب ميزة كتابة اليوميات مع مطالبات الذكاء الاصطناعي. تساعدني على التفكير بعمق أكبر في أفكاري ومشاعري.',
    'testimonials.3-author': 'إيما ل',

    // Pricing Preview
    'pricing-preview.title': 'اختر خطة العافية الخاصة بك',
    'pricing-preview.free': 'مجاني',
    'pricing-preview.plus': 'بلس',
    'pricing-preview.premium': 'بريميوم',
    'pricing-preview.free-desc': 'تتبع العافية الأساسي',
    'pricing-preview.plus-desc': 'تدريب ذكي ورؤى',
    'pricing-preview.premium-desc': 'مجموعة العافية الكاملة',
    'pricing-preview.cta': 'عرض جميع الخطط',

    // Pricing Page
    'pricing.title': 'اختر خطتك',
    'pricing.subtitle': 'ابدأ رحلة عافيتك بالخطة التي تناسب احتياجاتك.',
    'pricing.monthly': 'شهري',
    'pricing.annual': 'سنوي',
    'pricing.save': 'وفر 50%',

    // Free Plan
    'pricing.free.name': 'مجاني',
    'pricing.free.price': '$0',
    'pricing.free.period': '/شهر',
    'pricing.free.annual-price': '$0',
    'pricing.free.annual-period': '/سنة',
    'pricing.free.description': 'مثالي للبدء بتتبع العافية الأساسي.',
    'pricing.free.feature1': 'تتبع المزاج الأساسي',
    'pricing.free.feature2': '5 مدخلات يومية شهرياً',
    'pricing.free.feature3': 'رؤى النوم الأساسية',
    'pricing.free.feature4': 'مكتبة تأمل محدودة',
    'pricing.free.not-included1': 'تدريب صوتي ذكي',
    'pricing.free.not-included2': 'تحليلات متقدمة',
    'pricing.free.not-included3': 'كتابة يوميات غير محدودة',
    'pricing.free.not-included4': 'محتوى تأمل مميز',
    'pricing.free.button': 'ابدأ مجاناً',

    // Plus Plan
    'pricing.plus.name': 'بلس',
    'pricing.plus.price': '$4.99',
    'pricing.plus.period': '/شهر',
    'pricing.plus.annual-price': '$29.94',
    'pricing.plus.annual-period': '/سنة',
    'pricing.plus.description': 'ميزات محسّنة مع تدريب ذكي لرؤى أعمق.',
    'pricing.plus.feature1': 'كل شيء في المجاني',
    'pricing.plus.feature2': 'جلسات تدريب صوتي ذكي',
    'pricing.plus.feature3': 'كتابة يوميات غير محدودة',
    'pricing.plus.feature4': 'تحليلات مزاج متقدمة',
    'pricing.plus.feature5': 'رؤى مخصصة',
    'pricing.plus.feature6': 'مكتبة تأمل موسعة',
    'pricing.plus.not-included1': 'دعم أولوية',
    'pricing.plus.not-included2': 'تحليل نوم متقدم',
    'pricing.plus.button': 'ابدأ خطة بلس',

    // Premium Plan
    'pricing.premium.name': 'بريميوم',
    'pricing.premium.price': '$9.99',
    'pricing.premium.period': '/شهر',
    'pricing.premium.annual-price': '$59.94',
    'pricing.premium.annual-period': '/سنة',
    'pricing.premium.description': 'مجموعة العافية الكاملة مع جميع الميزات ودعم الأولوية.',
    'pricing.premium.feature1': 'كل شيء في بلس',
    'pricing.premium.feature2': 'تحليل نوم متقدم',
    'pricing.premium.feature3': 'دعم عملاء أولوية',
    'pricing.premium.feature4': 'تحديات العافية',
    'pricing.premium.feature5': 'تصدير البيانات والتقارير',
    'pricing.premium.feature6': 'مشاركة عائلية (حتى 4 أعضاء)',
    'pricing.premium.feature7': 'وصول مبكر للميزات الجديدة',
    'pricing.premium.feature8': 'خطط عافية مخصصة',
    'pricing.premium.button': 'ابدأ خطة بريميوم',

    // FAQ
    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'اعثر على إجابات للأسئلة الشائعة حول نوفيا مايند.',
    'faq.question1': 'هل يمكنني تغيير خطتي في أي وقت؟',
    'faq.answer1': 'نعم، يمكنك ترقية أو تخفيض خطتك في أي وقت. ستنعكس التغييرات في دورة الفوترة التالية.',
    'faq.question2': 'هل هناك تجربة مجانية؟',
    'faq.answer2': 'نقدم خطة مجانية بميزات أساسية. يمكنك الترقية إلى بلس أو بريميوم في أي وقت للوصول إلى الميزات المتقدمة.',
    'faq.question3': 'كيف يعمل التدريب الذكي؟',
    'faq.answer3': 'مدربنا الذكي يقدم إرشاداً مخصصاً بناءً على أنماط مزاجك ومدخلات يومياتك وأهداف عافيتك باستخدام التعلم الآلي المتقدم.',

    // About Page
    'about.title': 'حول نوفيا مايند',
    'about.subtitle': 'نحن في مهمة لجعل العافية النفسية متاحة للجميع من خلال تقنية الذكاء الاصطناعي المبتكرة.',
    'about.mission.title': 'مهمتنا',
    'about.mission.content': 'إضفاء الطابع الديمقراطي على العافية النفسية من خلال توفير تدريب مخصص مدعوم بالذكاء الاصطناعي يتكيف مع احتياجات وظروف كل فرد الفريدة.',
    'about.story.title': 'قصتنا',
    'about.story.content': 'تأسست من قبل متخصصين في الصحة النفسية وخبراء الذكاء الاصطناعي، وُلد نوفيا مايند من إدراك أن موارد الصحة النفسية التقليدية ليست متاحة للجميع.',
    'about.values.title': 'قيمنا',
    'about.values.privacy.title': 'الخصوصية أولاً',
    'about.values.privacy.desc': 'بيانات صحتك النفسية مقدسة. نستخدم التشفير من طرف إلى طرف ولا نشارك معلوماتك الشخصية أبداً.',
    'about.values.accessibility.title': 'متاح للجميع',
    'about.values.accessibility.desc': 'العافية النفسية لا يجب أن تكون رفاهية. نحن ملتزمون بجعل أدواتنا ميسورة التكلفة وشاملة.',
    'about.values.evidence.title': 'قائم على الأدلة',
    'about.values.evidence.desc': 'نهجنا مؤسس على البحث العلمي والتقنيات العلاجية المعتمدة.',
    'about.impact.title': 'تأثيرنا',
    'about.impact.users': 'المستخدمون النشطون',
    'about.impact.sessions': 'جلسات التدريب',
    'about.impact.satisfaction': 'رضا المستخدمين',

    // Contact Page
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'لديك أسئلة أو تحتاج دعم؟ نحن هنا لمساعدتك في رحلة عافيتك.',
    'contact.form.name': 'اسمك',
    'contact.form.email': 'عنوان البريد الإلكتروني',
    'contact.form.message': 'الرسالة',
    'contact.form.send': 'إرسال الرسالة',
    'contact.email-support': 'دعم البريد الإلكتروني',
    'contact.response-time': 'نرد عادة خلال 24 ساعة',
    'contact.faq.title': 'الأسئلة الشائعة',
    'contact.faq.1.q': 'كيف أعيد تعيين كلمة المرور؟',
    'contact.faq.1.a': 'يمكنك إعادة تعيين كلمة المرور بالنقر على "نسيت كلمة المرور" في شاشة تسجيل الدخول واتباع التعليمات المرسلة إلى بريدك الإلكتروني.',
    'contact.faq.2.q': 'هل بياناتي آمنة؟',
    'contact.faq.2.a': 'نعم، نستخدم التشفير من طرف إلى طرف ونتبع أفضل الممارسات الصناعية لحماية معلوماتك الشخصية.',
    'contact.faq.3.q': 'هل يمكنني إلغاء اشتراكي في أي وقت؟',
    'contact.faq.3.a': 'بالطبع. يمكنك إلغاء اشتراكك في أي وقت من خلال إعدادات حسابك أو متجر التطبيقات.',

    // Business Page
    'business.title': 'نوفيا مايند للمدارس',
    'business.subtitle': 'ادعم الصحة النفسية ورفاهية الطلاب بمنصة العافية الشاملة المصممة للمؤسسات التعليمية.',
    'business.benefits.student-wellbeing.title': 'رفاهية الطلاب',
    'business.benefits.student-wellbeing.desc': 'وفر للطلاب وصولاً على مدار الساعة لدعم الصحة النفسية وموارد العافية.',
    'business.benefits.analytics.title': 'التحليلات والرؤى',
    'business.benefits.analytics.desc': 'احصل على رؤى مجهولة الهوية حول اتجاهات عافية الطلاب لإعلام برامج الدعم.',
    'business.benefits.privacy.title': 'الخصوصية والأمان',
    'business.benefits.privacy.desc': 'منصة متوافقة مع FERPA مع حماية خصوصية قوية لبيانات الطلاب.',
    'business.benefits.management.title': 'إدارة سهلة',
    'business.benefits.management.desc': 'لوحة تحكم إدارية بسيطة لإدارة حسابات الطلاب ومراقبة المشاركة.',
    'business.packages.title': 'اختر حزمتك',
    'business.packages.small.title': 'مدرسة صغيرة',
    'business.packages.small.students': 'حتى 1,000 طالب',
    'business.packages.small.price': '$2.99/طالب/شهر',
    'business.packages.small.features.1': 'تتبع العافية الأساسي',
    'business.packages.small.features.2': 'جلسات تدريب ذكي',
    'business.packages.small.features.3': 'لوحة تحكم إدارية',
    'business.packages.small.features.4': 'دعم بريد إلكتروني',
    'business.packages.medium.title': 'مدرسة متوسطة',
    'business.packages.medium.students': '1,000 - 5,000 طالب',
    'business.packages.medium.price': '$2.49/طالب/شهر',
    'business.packages.medium.features.1': 'كل شيء في الصغيرة',
    'business.packages.medium.features.2': 'تحليلات متقدمة',
    'business.packages.medium.features.3': 'علامة تجارية مخصصة',
    'business.packages.medium.features.4': 'دعم أولوية',
    'business.packages.large.title': 'مدرسة كبيرة',
    'business.packages.large.students': '5,000+ طالب',
    'business.packages.large.price': 'تسعير مخصص',
    'business.packages.large.features.1': 'كل شيء في المتوسطة',
    'business.packages.large.features.2': 'مدير حساب مخصص',
    'business.packages.large.features.3': 'تكاملات مخصصة',
    'business.packages.large.features.4': 'دعم هاتفي على مدار الساعة',
    'business.form.title': 'ابدأ اليوم',
    'business.form.subtitle': 'تواصل معنا لتعرف المزيد عن جلب نوفيا مايند إلى مدرستك.',
    'business.form.school-name': 'اسم المدرسة',
    'business.form.student-count': 'عدد الطلاب',
    'business.form.student-count.placeholder': 'اختر عدد الطلاب',
    'business.form.student-count.less-1000': 'أقل من 1,000',
    'business.form.student-count.1000-5000': '1,000 - 5,000',
    'business.form.student-count.5000-10000': '5,000 - 10,000',
    'business.form.student-count.10000-plus': '10,000+',
    'business.form.contact-person': 'الشخص المسؤول',
    'business.form.email': 'عنوان البريد الإلكتروني',
    'business.form.notes': 'ملاحظات إضافية',
    'business.form.notes.placeholder': 'أخبرنا عن احتياجاتك المحددة أو أسئلتك...',
    'business.form.submit': 'طلب معلومات',

    // Footer
    'footer.company': 'تمكين العافية النفسية من خلال التدريب المدعوم بالذكاء الاصطناعي والرؤى المخصصة.',
    'footer.quick-links': 'روابط سريعة',
    'footer.resources': 'الموارد',
    'footer.legal': 'قانوني',
    'footer.legal.privacy': 'سياسة الخصوصية',
    'footer.legal.terms': 'الشروط والأحكام',
    'footer.legal.medical': 'إخلاء المسؤولية الطبية',
    'footer.legal.cookies': 'سياسة ملفات تعريف الارتباط',
    'footer.legal.refund': 'سياسة الاسترداد',
    'footer.legal.data-deletion': 'حذف البيانات',
    'footer.legal.eula': 'اتفاقية ترخيص المستخدم النهائي',
    'footer.legal.accessibility': 'إمكانية الوصول',
    'footer.legal.security-practices': 'ممارسات الأمان',
    'footer.copyright': '© 2025 نوفيا مايند. جميع الحقوق محفوظة.',

    // Live Chat
    'chat.welcome': 'مرحباً! أنا هنا لمساعدتك في أي أسئلة حول نوفيا مايند. كيف يمكنني مساعدتك اليوم؟',
    'chat.response': 'شكراً لرسالتك! سيرد عليك أحد وكلاء الدعم قريباً. في هذه الأثناء، يمكنك مراجعة الأسئلة الشائعة أو التواصل معنا على support@nuviamind.com',
    'chat.tooltip': 'تحدث معنا!',
    'chat.title': 'الدعم المباشر',
    'chat.subtitle': 'نحن هنا لمساعدتك!',
    'chat.placeholder': 'اكتب رسالتك...',

    // Cookie Consent
    'cookie-consent.title': 'تحليلات صديقة للخصوصية',
    'cookie-consent.subtitle': 'ساعدنا في تحسين تجربتك',
    'cookie-consent.description': 'نستخدم تحليلات صديقة للخصوصية لفهم كيفية استخدام الزوار لموقعنا. لا بيانات شخصية أو ملفات تعريف ارتباط أو تتبع عبر مواقع أخرى.',
    'cookie-consent.what-we-track': 'ما نتتبعه:',
    'cookie-consent.track.page-views': 'مشاهدات الصفحات المجهولة',
    'cookie-consent.track.button-clicks': 'نقرات الأزرار والتفاعلات',
    'cookie-consent.track.navigation': 'أنماط التنقل',
    'cookie-consent.track.referrers': 'مصادر الزيارات',
    'cookie-consent.what-we-dont-track': 'ما لا نتتبعه:',
    'cookie-consent.no-track.personal-info': 'المعلومات الشخصية أو عناوين IP',
    'cookie-consent.no-track.cross-site': 'التتبع عبر المواقع',
    'cookie-consent.no-track.cookies': 'ملفات تعريف الارتباط للتتبع',
    'cookie-consent.no-track.health-data': 'البيانات الصحية أو الحساسة',
    'cookie-consent.learn-more': 'تعرف على المزيد حول تتبعنا',
    'cookie-consent.show-less': 'إظهار أقل',
    'cookie-consent.accept': 'قبول التحليلات',
    'cookie-consent.decline': 'رفض',
    'cookie-consent.policy-link-text': 'اقرأ',
    'cookie-consent.privacy-policy': 'سياسة الخصوصية',
    'cookie-consent.and': 'و',
    'cookie-consent.cookie-policy': 'سياسة ملفات تعريف الارتباط',

    // Security Form
    'security-form.notice': 'هذا النموذج محمي بالتشفير وحماية الخصوصية',
    'security-form.data-notice': 'بياناتك مشفرة ومحمية. نحن لا نخزن المعلومات الشخصية دون ضرورة.',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.pricing': 'Precios',
    'nav.contact': 'Contacto',
    'nav.faq': 'Preguntas Frecuentes',
    'nav.business': 'Para Escuelas',
    'nav.blog': 'Blog',
    'nav.get-started': 'Comenzar',

    // Home Page
    'home.hero.title': 'Tu Guía de IA para la Mente, el Sueño y el Bienestar',
    'home.hero.subtitle': 'TPotencia tu bienestar mental con coaching de voz personalizado, autodescubrimiento, apoyo diario, conciencia emocional, mejor descanso y mindfulness',
    'home.hero.download': 'Descargar App',
    'home.hero.learn-more': 'Saber Más',

    // Features
    'features.title': 'Todo lo que Necesitas para tu Bienestar Mental',
    'features.ai-coach': 'Entrenador de voz con IA',
    'features.ai-coach-desc': 'Recibe orientación y apoyo personalizado de tu coach de bienestar con IA, disponible las 24 horas.',
    'features.journaling': 'Diario Inteligente',
    'features.journaling-desc': 'Expresa tus pensamientos con sugerencias e insights potenciados por IA para profundizar en tu autorreflexión.',
    'features.mood-tracker': 'Seguimiento del Estado de Ánimo',
    'features.mood-tracker-desc': 'Monitorea tus patrones emocionales y descubre qué factores influyen en tu bienestar.',
    'features.sleep-insights': 'Análisis del sueño',
    'features.sleep-insights-desc': 'Comprende tus patrones de sueño y recibe recomendaciones personalizadas para descansar mejor.',
    'features.meditation': 'Meditación Guiada',
    'features.meditation-desc': 'Accede a una biblioteca de sesiones de meditación diseñadas especialmente para tus necesidades y preferencias.',
    'features.tracking': 'Seguimiento del Progreso',
    'features.tracking-desc': 'Visualiza tu camino hacia el bienestar con análisis detallados e informes de progreso.',
    'features.affirmations': 'Afirmaciones Diarias',
    'features.affirmations-desc': 'Inicia cada día con afirmaciones personalizadas que fortalecen tu confianza y positividad.',
    'features.challenges': 'Desafíos de Bienestar',
    'features.challenges-desc': 'Participa en desafíos guiados para desarrollar hábitos saludables y alcanzar tus metas.',

    // How It Works
    'how-it-works.title': 'Cómo Funciona NuviaMind',
    'how-it-works.step1': 'Descargar y Configurar',
    'how-it-works.step1-desc': 'Descarga la aplicación y completa tu evaluación personalizada de bienestar.',
    'how-it-works.step2': 'Obtén Coaching Personalizado',
    'how-it-works.step2-desc': 'Recibe insights y coaching potenciado por IA, adaptado a tus necesidades únicas.',
    'how-it-works.step3': 'Sigue tu Progreso',
    'how-it-works.step3-desc': 'Monitorea tu camino hacia el bienestar y celebra cada logro.',

    // Testimonials
    'testimonials.title': 'Lo que Dicen Nuestros Usuarios',
    'testimonials.1': 'NuviaMind ha transformado por completo mi enfoque hacia el bienestar mental. El coach de IA es como tener un terapeuta personal disponible en cualquier momento.',
    'testimonials.1-author': 'Sarah M.',
    'testimonials.2': 'Los análisis del sueño me han ayudado a entender mis patrones y mejorar considerablemente la calidad de mi descanso.',
    'testimonials.2-author': 'Michael R.',
    'testimonials.3': 'Me fascina la función de diario con sugerencias de IA. Me ayuda a reflexionar más profundamente sobre mis pensamientos y emociones.',
    'testimonials.3-author': 'Emma L.',

    // Pricing Preview
    'pricing-preview.title': 'Elige tu Plan de Bienestar',
    'pricing-preview.free': 'Gratis',
    'pricing-preview.plus': 'Plus',
    'pricing-preview.premium': 'Premium',
    'pricing-preview.free-desc': 'Seguimiento básico de bienestar',
    'pricing-preview.plus-desc': 'Coaching con IA e insights',
    'pricing-preview.premium-desc': 'Suite completa de bienestar',
    'pricing-preview.cta': 'Ver Todos los Planes',

    // Pricing Page
    'pricing.title': 'Elige Tu Plan',
    'pricing.subtitle': 'Tu bienestar empieza aquí: elige el plan perfecto para tus necesidades',
    'pricing.monthly': 'Mensual',
    'pricing.annual': 'Anual',
    'pricing.save': 'Ahorra 50%',

    // Free Plan
    'pricing.free.name': 'Gratis',
    'pricing.free.price': '$0',
    'pricing.free.period': '/mes',
    'pricing.free.annual-price': '$0',
    'pricing.free.annual-period': '/año',
    'pricing.free.description': 'Ideal para comenzar con el seguimiento básico de tu bienestar.',
    'pricing.free.feature1': 'Seguimiento básico del estado de ánimo',
    'pricing.free.feature2': '5 entradas de diario por mes',
    'pricing.free.feature3': 'Análisis básicos del sueño',
    'pricing.free.feature4': 'Biblioteca limitada de meditación',
    'pricing.free.not-included1': 'Coaching de voz con IA',
    'pricing.free.not-included2': 'Análisis avanzados',
    'pricing.free.not-included3': 'Diario ilimitado',
    'pricing.free.not-included4': 'Contenido exclusivo de meditación',
    'pricing.free.button': 'Comenzar Gratis',

    // Plus Plan
    'pricing.plus.name': 'Plus',
    'pricing.plus.price': '$4.99',
    'pricing.plus.period': '/mes',
    'pricing.plus.annual-price': '$29.94',
    'pricing.plus.annual-period': '/año',
    'pricing.plus.description': 'Funciones mejoradas con coaching de IA para insights más profundos.',
    'pricing.plus.feature1': 'Todo en Gratis',
    'pricing.plus.feature2': 'Sesiones de coaching de voz con IA',
    'pricing.plus.feature3': 'Diario ilimitado',
    'pricing.plus.feature4': 'Análisis avanzado del estado de ánimo',
    'pricing.plus.feature5': 'Análisis personalizados',
    'pricing.plus.feature6': 'Biblioteca extendida de meditación',
    'pricing.plus.not-included1': 'Soporte prioritario',
    'pricing.plus.not-included2': 'Análisis avanzado del sueño',
    'pricing.plus.button': 'Comenzar Plan Plus',

    // Premium Plan
    'pricing.premium.name': 'Premium',
    'pricing.premium.price': '$9.99',
    'pricing.premium.period': '/mes',
    'pricing.premium.annual-price': '$59.94',
    'pricing.premium.annual-period': '/año',
    'pricing.premium.description': 'Suite completa de bienestar con todas las funciones y soporte prioritario.',
    'pricing.premium.feature1': 'Todo en Plus',
    'pricing.premium.feature2': 'Análisis avanzado del sueño',
    'pricing.premium.feature3': 'Soporte al cliente prioritario',
    'pricing.premium.feature4': 'Desafíos de bienestar',
    'pricing.premium.feature5': 'Exportar datos e informes',
    'pricing.premium.feature6': 'Plan familiar (hasta 4 miembros)',
    'pricing.premium.feature7': 'Acceso anticipado a nuevas funciones',
    'pricing.premium.feature8': 'Planes de bienestar personalizados',
    'pricing.premium.button': 'Comenzar Plan Premium',

    // FAQ
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Encuentra respuestas a las preguntas más comunes sobre NuviaMind.',
    'faq.question1': '¿Puedo cambiar mi plan en cualquier momento?',
    'faq.answer1': 'Sí, puedes actualizar o cambiar tu plan en cualquier momento. Los cambios se aplicarán en tu próximo ciclo de facturación.',
    'faq.question2': '¿Hay una prueba gratuita?',
    'faq.answer2': 'Ofrecemos un plan gratuito con funciones básicas. Puedes actualizar a Plus o Premium en cualquier momento para acceder a funciones avanzadas.',
    'faq.question3': '¿Cómo funciona el coaching con IA?',
    'faq.answer3': 'Nuestro coach de IA te brinda orientación personalizada basada en tus patrones de estado de ánimo, entradas de diario y objetivos de bienestar, utilizando tecnología de aprendizaje automático avanzado.',

    // About Page
    'about.title': 'Nosotros',
    'about.subtitle': 'Nuestra misión es hacer el bienestar mental accesible para todos a través de tecnología de IA innovadora.',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.content': 'Democratizar el bienestar mental brindando coaching personalizado potenciado por IA que se adapta a las necesidades y circunstancias únicas de cada persona.',
    'about.story.title': 'Nuestra Historia',
    'about.story.content': 'Fundada por profesionales de la salud mental y expertos en IA, NuviaMind nació del reconocimiento de que los recursos tradicionales de salud mental no están al alcance de todos.',
    'about.values.title': 'Nuestros Valores',
    'about.values.privacy.title': 'Privacidad Primero',
    'about.values.privacy.desc': 'Tus datos de salud mental son sagrados. Utilizamos cifrado de extremo a extremo y nunca compartimos tu información personal.',
    'about.values.accessibility.title': 'Accesible para Todos',
    'about.values.accessibility.desc': 'El bienestar mental no debe ser un lujo. Nos comprometemos a hacer nuestras herramientas accesibles e inclusivas.',
    'about.values.evidence.title': 'Basado en Evidencia',
    'about.values.evidence.desc': 'Nuestros métodos se fundamentan en investigación científica y técnicas terapéuticas validadas.',
    'about.impact.title': 'Nuestro Impacto',
    'about.impact.users': 'Usuarios Activos',
    'about.impact.sessions': 'Sesiones de Coaching',
    'about.impact.satisfaction': 'Satisfacción de Usuarios',

    // Contact Page
    'contact.title': 'Contáctanos',
    'contact.subtitle': '¿Tienes preguntas o necesitas apoyo? Estamos aquí para acompañarte en tu camino hacia el bienestar.',
    'contact.form.name': 'Tu Nombre',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'contact.email-support': 'Soporte por Email',
    'contact.response-time': 'Normalmente respondemos en menos de 24 horas',
    'contact.faq.title': 'Preguntas Frecuentes',
    'contact.faq.1.q': '¿Cómo restablezco mi contraseña?',
    'contact.faq.1.a': 'Puedes restablecer tu contraseña haciendo clic en "Olvidé mi contraseña" en la pantalla de inicio de sesión y siguiendo las instrucciones que te enviaremos por correo.',
    'contact.faq.2.q': '¿Están seguros mis datos?',
    'contact.faq.2.a': 'Absolutamente. Utilizamos cifrado de extremo a extremo y seguimos las mejores prácticas de la industria para proteger tu información personal.',
    'contact.faq.3.q': '¿Puedo cancelar mi suscripción en cualquier momento?',
    'contact.faq.3.a': 'Por supuesto. Puedes cancelar tu suscripción en cualquier momento desde la configuración de tu cuenta o la tienda de aplicaciones.',

    // Business Page
    'business.title': 'NuviaMind para Escuelas',
    'business.subtitle': 'Apoya la salud mental y el bienestar estudiantil con nuestra plataforma integral de bienestar diseñada especialmente para instituciones educativas.',
    'business.benefits.student-wellbeing.title': 'Bienestar Estudiantil',
    'business.benefits.student-wellbeing.desc': 'Brinda a los estudiantes acceso las 24 horas a apoyo de salud mental y recursos de bienestar.',
    'business.benefits.analytics.title': 'Análisis y Datos',
    'business.benefits.analytics.desc': 'Obtén información anónima sobre tendencias de bienestar estudiantil para mejorar los programas de apoyo.',
    'business.benefits.privacy.title': 'Privacidad y Seguridad',
    'business.benefits.privacy.desc': 'Plataforma compatible con FERPA que incluye protecciones sólidas de privacidad para los datos estudiantiles.',
    'business.benefits.management.title': 'Gestión Fácil',
    'business.benefits.management.desc': 'Panel de administración sencillo para gestionar cuentas estudiantiles y monitorear la participación.',
    'business.packages.title': 'Elige Tu Paquete',
    'business.packages.small.title': 'Escuela Pequeña',
    'business.packages.small.students': 'Hasta 1,000 estudiantes',
    'business.packages.small.price': '$2.99/estudiante/mes',
    'business.packages.small.features.1': 'Seguimiento básico de bienestar',
    'business.packages.small.features.2': 'Sesiones de coaching con IA',
    'business.packages.small.features.3': 'Panel de administración',
    'business.packages.small.features.4': 'Soporte por email',
    'business.packages.medium.title': 'Escuela Mediana',
    'business.packages.medium.students': '1,000 - 5,000 estudiantes',
    'business.packages.medium.price': '$2.49/estudiante/mes',
    'business.packages.medium.features.1': 'Todo en Pequeña',
    'business.packages.medium.features.2': 'Análisis avanzados',
    'business.packages.medium.features.3': 'Personalización de marca',
    'business.packages.medium.features.4': 'Soporte prioritario',
    'business.packages.large.title': 'Escuela Grande',
    'business.packages.large.students': '5,000+ estudiantes',
    'business.packages.large.price': 'Cotización personalizada',
    'business.packages.large.features.1': 'Todo en Mediana',
    'business.packages.large.features.2': 'Gestor de cuenta dedicado',
    'business.packages.large.features.3': 'Integraciones personalizadas',
    'business.packages.large.features.4': 'Soporte telefónico 24/7',
    'business.form.title': 'Comienza Hoy Mismo',
    'business.form.subtitle': 'Contáctanos para conocer más sobre cómo llevar NuviaMind a tu institución educativa.',
    'business.form.school-name': 'Nombre de la Escuela',
    'business.form.student-count': 'Número de Estudiantes',
    'business.form.student-count.placeholder': 'Selecciona el número de estudiantes',
    'business.form.student-count.less-1000': 'Menos de 1,000',
    'business.form.student-count.1000-5000': '1,000 - 5,000',
    'business.form.student-count.5000-10000': '5,000 - 10,000',
    'business.form.student-count.10000-plus': '10,000+',
    'business.form.contact-person': 'Persona de Contacto',
    'business.form.email': 'Correo Electrónico',
    'business.form.notes': 'Notas Adicionales',
    'business.form.notes.placeholder': 'Cuéntanos sobre las necesidades específicas de tu institución o cualquier pregunta que tengas...',
    'business.form.submit': 'Solicitar Información',

    // Footer
    'footer.company': 'Transformando el bienestar mental a través de coaching potenciado por IA y análisis personalizados.',
    'footer.quick-links': 'Enlaces Rápidos',
    'footer.resources': 'Recursos',
    'footer.legal': 'Legal',
    'footer.legal.privacy': 'Política de Privacidad',
    'footer.legal.terms': 'Términos y Condiciones',
    'footer.legal.medical': 'Aviso Médico',
    'footer.legal.cookies': 'Política de Cookies',
    'footer.legal.refund': 'Política de Reembolso',
    'footer.legal.data-deletion': 'Eliminación de Datos',
    'footer.legal.eula': 'EULA',
    'footer.legal.accessibility': 'Accesibilidad',
    'footer.legal.security-practices': 'Prácticas de Seguridad',
    'footer.copyright': '© 2025 NuviaMind. Todos los derechos reservados.',

    // Live Chat
    'chat.welcome': '¡Hola! Estoy aquí para ayudarte con cualquier pregunta sobre NuviaMind. ¿Cómo puedo asistirte hoy?',
    'chat.response': '¡Gracias por tu mensaje! Un agente de soporte te responderá pronto. Mientras tanto, puedes revisar nuestras preguntas frecuentes o contactarnos en support@nuviamind.com',
    'chat.tooltip': '¡Chatea con nosotros!',
    'chat.title': 'Soporte en Vivo',
    'chat.subtitle': '¡Estamos aquí para ayudarte!',
    'chat.placeholder': 'Escribe tu mensaje...',

    // Cookie Consent
    'cookie-consent.title': 'Analíticas Respetuosas con la Privacidad',
    'cookie-consent.subtitle': 'Ayúdanos a mejorar tu experiencia',
    'cookie-consent.description': 'Utilizamos analíticas respetuosas con la privacidad para entender cómo los visitantes usan nuestro sitio web. Sin datos personales, cookies o seguimiento en otros sitios.',
    'cookie-consent.what-we-track': 'Lo que rastreamos:',
    'cookie-consent.track.page-views': 'Vistas de página anónimas',
    'cookie-consent.track.button-clicks': 'Clics de botones e interacciones',
    'cookie-consent.track.navigation': 'Patrones de navegación',
    'cookie-consent.track.referrers': 'Fuentes de tráfico',
    'cookie-consent.what-we-dont-track': 'Lo que NO rastreamos:',
    'cookie-consent.no-track.personal-info': 'Información personal o direcciones IP',
    'cookie-consent.no-track.cross-site': 'Seguimiento entre sitios',
    'cookie-consent.no-track.cookies': 'Cookies de seguimiento',
    'cookie-consent.no-track.health-data': 'Datos de salud o sensibles',
    'cookie-consent.learn-more': 'Aprende más sobre nuestro seguimiento',
    'cookie-consent.show-less': 'Mostrar menos',
    'cookie-consent.accept': 'Aceptar Analíticas',
    'cookie-consent.decline': 'Rechazar',
    'cookie-consent.policy-link-text': 'Lee nuestra',
    'cookie-consent.privacy-policy': 'Política de Privacidad',
    'cookie-consent.and': 'y',
    'cookie-consent.cookie-policy': 'Política de Cookies',

    // Security Form
    'security-form.notice': 'Este formulario está protegido con cifrado y protección de privacidad',
    'security-form.data-notice': 'Tus datos están cifrados y protegidos. Nunca almacenamos información personal innecesariamente.',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}